server:
  port: 8002

spring:
  application:
    name: users-service

  datasource:
    url: jdbc:mysql://localhost:3307/innovatech_users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERS_USER:root}
    password: ${DB_USERS_PASS:innovatech2024}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:clave-secreta-super-segura-para-desarrollo}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
