CREATE TABLE projects (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    descripcion TEXT NULL,
    estado ENUM('PLANIFICADO', 'EN_PROGRESO', 'COMPLETADO', 'CERRADO') NOT NULL DEFAULT 'PLANIFICADO',
    prioridad ENUM('ALTA', 'MEDIA', 'BAJA') NOT NULL DEFAULT 'MEDIA',
    fecha_inicio DATE NULL,
    fecha_fin DATE NULL,
    responsable_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
